# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
pool:
  vmImage: ubuntu-latest
variables:
- name: var1
  value: "var1value"

stages:
  - stage: s1
    jobs:
    - job: js1j1
      steps: js1j1s1
      - bash: echo "js1j1s1"
    - job: js1j2
      steps: js1j1s2
      - bash: echo "js1j1s2"
  - stage: s2