# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
pool:
  vmImage: ubuntu-latest
variables:
- name: var1
  value: "var1value"

stages:
  - stage: s1
    jobs:
    - job: js1j1
      steps:
      - bash: echo "js1j1s1"
    - job: js1j2
      steps:
        - bash: echo "js1j2s1"
  - stage: s2
    dependsOn: []
    jobs:
    - job: s2j1
      steps:
        - bash: echo "s2j1 "
  - stage: s3
    dependsOn: []
    jobs:
    - job: s3j1
      steps:
        - bash: echo "s3j1"

